const data = [
	{
		"APELLIDOP": "HERNANDEZ",
		"APELLIDOM": "VALENCIA",
		"NOMBRECOMPLETO": "DANNA SOFIA",
		"FECHANACIMIENTO": "6/26/2022",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "HVDS2022"
	},
	{
		"APELLIDOP": "CASTILLO",
		"APELLIDOM": "DONATO",
		"NOMBRECOMPLETO": "ANDRES OMAR",
		"FECHANACIMIENTO": "8/14/2021",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "CDAO2021"
	},
	{
		"APELLIDOP": "HERNANDEZ",
		"APELLIDOM": "CORONEL",
		"NOMBRECOMPLETO": "AURIS YARETZI",
		"FECHANACIMIENTO": "9/28/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "HCAY2021"
	},
	{
		"APELLIDOP": "MARTINEZ ",
		"APELLIDOM": "SANTAMARIA",
		"NOMBRECOMPLETO": "FERNANDA",
		"FECHANACIMIENTO": "8/10/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "MSF2021"
	},
	{
		"APELLIDOP": "RAMIREZ ",
		"APELLIDOM": "VEGA",
		"NOMBRECOMPLETO": "ANTONELLA",
		"FECHANACIMIENTO": "11/14/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "RVA2021"
	},
	{
		"APELLIDOP": "RIOS",
		"APELLIDOM": "CAMPOS",
		"NOMBRECOMPLETO": "CAMILA",
		"FECHANACIMIENTO": "7/10/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "RCC2021"
	},
	{
		"APELLIDOP": "RODRIGUEZ",
		"APELLIDOM": "CARRADA",
		"NOMBRECOMPLETO": "MIA VICTORIA",
		"FECHANACIMIENTO": "5/8/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "RCMV2021"
	},
	{
		"APELLIDOP": "TANNOS",
		"APELLIDOM": "NAVA",
		"NOMBRECOMPLETO": "ROCIO VALENTINA",
		"FECHANACIMIENTO": "9/21/2021",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "TNRV2021"
	},
	{
		"APELLIDOP": "VALLEJO",
		"APELLIDOM": "FLORES",
		"NOMBRECOMPLETO": "CALEB",
		"FECHANACIMIENTO": "9/4/2021",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "VFC2021"
	},
	{
		"APELLIDOP": "ESTRADA",
		"APELLIDOM": "VAZQUEZ",
		"NOMBRECOMPLETO": "NATALIA",
		"FECHANACIMIENTO": "6/30/2020",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "EVN2020"
	},
	{
		"APELLIDOP": "GAMBOA ",
		"APELLIDOM": "MERINO",
		"NOMBRECOMPLETO": "RANDY MAURICIO",
		"FECHANACIMIENTO": "12/12/2020",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "GMRM2020"
	},
	{
		"APELLIDOP": "LARUMBE ",
		"APELLIDOM": "LORENZANA",
		"NOMBRECOMPLETO": "NATALIA SHECCID",
		"FECHANACIMIENTO": "7/24/2020",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "LLNS2020"
	},
	{
		"APELLIDOP": "SEVILLA",
		"APELLIDOM": "MENDOZA",
		"NOMBRECOMPLETO": "ANGELA",
		"FECHANACIMIENTO": "11/3/2020",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREESCOLAR",
		"MATRICULA": "SMA2020"
	},
	{
		"APELLIDOP": "BONILLA",
		"APELLIDOM": "CASASOLA",
		"NOMBRECOMPLETO": "MATTEO",
		"FECHANACIMIENTO": "8/21/2019",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "PRIMARIA",
		"MATRICULA": "BCM2019"
	},
	{
		"APELLIDOP": "FOMBONA",
		"APELLIDOM": "GONZALEZ",
		"NOMBRECOMPLETO": "ALEXANDRE",
		"FECHANACIMIENTO": "6/15/2019",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FGA2019"
	},
	{
		"APELLIDOP": "GARCIA",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "MIRANDA JUDITH",
		"FECHANACIMIENTO": "12/5/2019",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PRIMARIA",
		"MATRICULA": "GCMJ2019"
	},
	{
		"APELLIDOP": "OCAMPO",
		"APELLIDOM": "CIPRIANO",
		"NOMBRECOMPLETO": "MAR ELISA",
		"FECHANACIMIENTO": "4/11/2019",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PRIMARIA",
		"MATRICULA": "OCME2019"
	},
	{
		"APELLIDOP": "SUASTEGUI",
		"APELLIDOM": "RIVERA",
		"NOMBRECOMPLETO": "EMILY MAIRIM",
		"FECHANACIMIENTO": "7/30/2029",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PRIMARIA",
		"MATRICULA": "SREM2029"
	},
	{
		"APELLIDOP": "ABELINO ",
		"APELLIDOM": "MARTINEZ",
		"NOMBRECOMPLETO": "YAHIR MATIAS",
		"FECHANACIMIENTO": "2/5/2018",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "AMYM2018"
	},
	{
		"APELLIDOP": "DIEGO ",
		"APELLIDOM": "CRUZ",
		"NOMBRECOMPLETO": "EVELYN LORELY",
		"FECHANACIMIENTO": "11/21/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "DCEL2018"
	},
	{
		"APELLIDOP": "GALEANA ",
		"APELLIDOM": "FLORES",
		"NOMBRECOMPLETO": "AZUL ANILETH",
		"FECHANACIMIENTO": "6/2/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "GFAA2018"
	},
	{
		"APELLIDOP": "SALGADO",
		"APELLIDOM": "MENDOZA",
		"NOMBRECOMPLETO": "MIA SOPHIA",
		"FECHANACIMIENTO": "1/13/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "SMMS2018"
	},
	{
		"APELLIDOP": "RODRIGUEZ",
		"APELLIDOM": "SUASTEGUI",
		"NOMBRECOMPLETO": "ESLY",
		"FECHANACIMIENTO": "11/12/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "RSE2018"
	},
	{
		"APELLIDOP": "TORRES",
		"APELLIDOM": "SANTOS",
		"NOMBRECOMPLETO": "CRISTIAN MARIETTE",
		"FECHANACIMIENTO": "6/4/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "TSCM2018"
	},
	{
		"APELLIDOP": "VILLA",
		"APELLIDOM": "SANTANDER",
		"NOMBRECOMPLETO": "ABRIL ALESSA",
		"FECHANACIMIENTO": "1/3/2018",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PRIMARIA",
		"MATRICULA": "VSAA2018"
	},
	{
		"APELLIDOP": "ARENAS",
		"APELLIDOM": "GARNICA",
		"NOMBRECOMPLETO": "EMELY SEKHMET",
		"FECHANACIMIENTO": "10/4/2017",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "AGES2017"
	},
	{
		"APELLIDOP": "BAUTISTA ",
		"APELLIDOM": "REYES",
		"NOMBRECOMPLETO": "CAMILA ISABELLA",
		"FECHANACIMIENTO": "6/7/2017",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "BRCI2017"
	},
	{
		"APELLIDOP": "CRISPIN",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "FERNANDA MICHELLE",
		"FECHANACIMIENTO": "12/15/2017",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "CCFM2017"
	},
	{
		"APELLIDOP": "MIRANDA",
		"APELLIDOM": "ELBJORN",
		"NOMBRECOMPLETO": "KARLA MICHELLE",
		"FECHANACIMIENTO": "10/27/2017",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "MEKM2017"
	},
	{
		"APELLIDOP": "MORALES",
		"APELLIDOM": "RADILLA",
		"NOMBRECOMPLETO": "JORGE LEONARDO",
		"FECHANACIMIENTO": "3/26/2017",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "MRJL2017"
	},
	{
		"APELLIDOP": "MORALES",
		"APELLIDOM": "VILLALOBOS ",
		"NOMBRECOMPLETO": "VICTORIA RUBI",
		"FECHANACIMIENTO": "5/11/2017",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "MVVR2017"
	},
	{
		"APELLIDOP": "RAMIREZ ",
		"APELLIDOM": "GARCIA",
		"NOMBRECOMPLETO": "HECTOR",
		"FECHANACIMIENTO": "6/12/2017",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "RGH2017"
	},
	{
		"APELLIDOP": "TRUJILLO",
		"APELLIDOM": "MARTINEZ",
		"NOMBRECOMPLETO": "SAMUEL",
		"FECHANACIMIENTO": "1/22/2017",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PRIMARIA",
		"MATRICULA": "TMS2017"
	},
	{
		"APELLIDOP": "ABELINO",
		"APELLIDOM": "MARTINEZ",
		"NOMBRECOMPLETO": "MARCO ABRAHAM",
		"FECHANACIMIENTO": "12/9/2015",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "AMMA2015"
	},
	{
		"APELLIDOP": "ALVARADO ",
		"APELLIDOM": "TOSCANO ",
		"NOMBRECOMPLETO": "MATEO SANTIAGO",
		"FECHANACIMIENTO": "5/1/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "ATMS2016"
	},
	{
		"APELLIDOP": "ARELLANO",
		"APELLIDOM": "VARGAS",
		"NOMBRECOMPLETO": "MARIA JOSE",
		"FECHANACIMIENTO": "11/16/2016",
		"SEXO": "F",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "AVMJ2016"
	},
	{
		"APELLIDOP": "CRUZ",
		"APELLIDOM": "DEL CARMEN",
		"NOMBRECOMPLETO": "PEDRO SEBASTIAN",
		"FECHANACIMIENTO": "2/3/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "CDPS2016"
	},
	{
		"APELLIDOP": "FOMBONA",
		"APELLIDOM": "GONZALEZ",
		"NOMBRECOMPLETO": "SEBASTIAN",
		"FECHANACIMIENTO": "12/17/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FGS2016"
	},
	{
		"APELLIDOP": "FLORES",
		"APELLIDOM": "AGATON",
		"NOMBRECOMPLETO": "ARANZA",
		"FECHANACIMIENTO": "3/19/2016",
		"SEXO": "F",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FAA2016"
	},
	{
		"APELLIDOP": "JIMENEZ",
		"APELLIDOM": "ESPINOZA",
		"NOMBRECOMPLETO": "ERICK GAEL",
		"FECHANACIMIENTO": "8/9/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "JEEG2016"
	},
	{
		"APELLIDOP": "LUEVANOS",
		"APELLIDOM": "LOPEZ",
		"NOMBRECOMPLETO": "REBECA GUADALUPE",
		"FECHANACIMIENTO": "12/12/2016",
		"SEXO": "F",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "LLRG2016"
	},
	{
		"APELLIDOP": "MEZA",
		"APELLIDOM": "VELAZQUEZ",
		"NOMBRECOMPLETO": "THIAGO MATEO",
		"FECHANACIMIENTO": "1/30/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "MVTM2016"
	},
	{
		"APELLIDOP": "RIVERA",
		"APELLIDOM": "ALMAZAN",
		"NOMBRECOMPLETO": "ANNIE CRISTAL",
		"FECHANACIMIENTO": "10/10/2015",
		"SEXO": "F",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "RAAC2015"
	},
	{
		"APELLIDOP": "RODRIGUEZ",
		"APELLIDOM": "CRUZ",
		"NOMBRECOMPLETO": "ARTURO TADEO",
		"FECHANACIMIENTO": "2/10/2016",
		"SEXO": "M",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "RCAT2016"
	},
	{
		"APELLIDOP": "SILVA",
		"APELLIDOM": "REYNA",
		"NOMBRECOMPLETO": "LIA QUETZALLI",
		"FECHANACIMIENTO": "3/27/2016",
		"SEXO": "F",
		"GRADO": "4",
		"SECCION": "PRIMARIA",
		"MATRICULA": "SRLQ2016"
	},
	{
		"APELLIDOP": "ABARCA",
		"APELLIDOM": "GARCIA",
		"NOMBRECOMPLETO": "GABRIEL ALEXANDER",
		"FECHANACIMIENTO": "2/25/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "AGGA2015"
	},
	{
		"APELLIDOP": "BALDERAS",
		"APELLIDOM": "ARIAS ",
		"NOMBRECOMPLETO": "JOSE ALEJANDRO",
		"FECHANACIMIENTO": "11/22/2014",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "BAJA2014"
	},
	{
		"APELLIDOP": "BENITEZ",
		"APELLIDOM": "GUTIERREZ",
		"NOMBRECOMPLETO": "YARETH ABIGAIL",
		"FECHANACIMIENTO": "11/24/2015",
		"SEXO": "F",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "BGYA2015"
	},
	{
		"APELLIDOP": "FLORES",
		"APELLIDOM": "CASTILLO",
		"NOMBRECOMPLETO": "JOSE MARIA",
		"FECHANACIMIENTO": "1/4/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FCJM2015"
	},
	{
		"APELLIDOP": "LAREDO",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "AXEL",
		"FECHANACIMIENTO": "1/5/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "LCA2015"
	},
	{
		"APELLIDOP": "LEMUS",
		"APELLIDOM": "SANTANA",
		"NOMBRECOMPLETO": "MAURO ISMAEL",
		"FECHANACIMIENTO": "7/13/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "LSMI2015"
	},
	{
		"APELLIDOP": "MARTINEZ",
		"APELLIDOM": "SANTAMARIA",
		"NOMBRECOMPLETO": "EMILIANO",
		"FECHANACIMIENTO": "10/10/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "MSE2015"
	},
	{
		"APELLIDOP": "ROSALES",
		"APELLIDOM": "VARGAS",
		"NOMBRECOMPLETO": "CARLOS ALBERTO",
		"FECHANACIMIENTO": "3/2/2015",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "RVCA2015"
	},
	{
		"APELLIDOP": "VARGAS",
		"APELLIDOM": "ABARCA",
		"NOMBRECOMPLETO": "MATIAS JOSUE",
		"FECHANACIMIENTO": "7/17/2014",
		"SEXO": "M",
		"GRADO": "5",
		"SECCION": "PRIMARIA",
		"MATRICULA": "VAMJ2014"
	},
	{
		"APELLIDOP": "CRISPIN",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "LEONEL SEBASTIAN",
		"FECHANACIMIENTO": "10/9/2014",
		"SEXO": "M",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "CCLS2014"
	},
	{
		"APELLIDOP": "FLORES",
		"APELLIDOM": "TEJADA",
		"NOMBRECOMPLETO": "ALESSANDRA",
		"FECHANACIMIENTO": "3/12/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FTA2014"
	},
	{
		"APELLIDOP": "FOMBONA",
		"APELLIDOM": "GONZALEZ",
		"NOMBRECOMPLETO": "GALA",
		"FECHANACIMIENTO": "5/30/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "FGG2014"
	},
	{
		"APELLIDOP": "GUTIERREZ",
		"APELLIDOM": "GONZALEZ",
		"NOMBRECOMPLETO": "AZUL CLARITA",
		"FECHANACIMIENTO": "10/15/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "GGAC2014"
	},
	{
		"APELLIDOP": "JIMENEZ",
		"APELLIDOM": "NUÑEZ",
		"NOMBRECOMPLETO": "KENIA JAZMIN",
		"FECHANACIMIENTO": "3/3/2013",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "JNKJ2013"
	},
	{
		"APELLIDOP": "LIRA ",
		"APELLIDOM": "SANCHEZ",
		"NOMBRECOMPLETO": "YAMILET",
		"FECHANACIMIENTO": "12/6/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "LSY2014"
	},
	{
		"APELLIDOP": "LUCENA",
		"APELLIDOM": "CORTEZ",
		"NOMBRECOMPLETO": "LIAM",
		"FECHANACIMIENTO": "4/3/2014",
		"SEXO": "M",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "LCL2014"
	},
	{
		"APELLIDOP": "TORRES",
		"APELLIDOM": "LOZANO",
		"NOMBRECOMPLETO": "SHARON ALEXA",
		"FECHANACIMIENTO": "10/22/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "TLSA2014"
	},
	{
		"APELLIDOP": "VALADEZ",
		"APELLIDOM": "BUSTAMANTE",
		"NOMBRECOMPLETO": "ALEXANDRA",
		"FECHANACIMIENTO": "4/12/2014",
		"SEXO": "F",
		"GRADO": "6",
		"SECCION": "PRIMARIA",
		"MATRICULA": "VBA2014"
	},
	{
		"APELLIDOP": "ALVARO",
		"APELLIDOM": "BARBERENA",
		"NOMBRECOMPLETO": "JONATHAN ULISES",
		"FECHANACIMIENTO": "12/5/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "ABJU2013"
	},
	{
		"APELLIDOP": "BETANCOURT",
		"APELLIDOM": "BIBIANO",
		"NOMBRECOMPLETO": "ROCIO DE LOS ANGELES",
		"FECHANACIMIENTO": "7/11/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "BBRA2013"
	},
	{
		"APELLIDOP": "COCTECON",
		"APELLIDOM": "CEDILLO",
		"NOMBRECOMPLETO": "DYLAN ALESSANDRO",
		"FECHANACIMIENTO": "4/2/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "CCDA2013"
	},
	{
		"APELLIDOP": "ESTRADA",
		"APELLIDOM": "MORALES",
		"NOMBRECOMPLETO": "HERIBERTO",
		"FECHANACIMIENTO": "6/24/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "EMH2013"
	},
	{
		"APELLIDOP": "ESPINOZA",
		"APELLIDOM": "ROMAN",
		"NOMBRECOMPLETO": "FABIAN",
		"FECHANACIMIENTO": "3/6/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "ERF2013"
	},
	{
		"APELLIDOP": "FENTON",
		"APELLIDOM": "CASASOLA",
		"NOMBRECOMPLETO": "ALESSANDRA",
		"FECHANACIMIENTO": "3/26/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "FCA2013"
	},
	{
		"APELLIDOP": "GALVEZ",
		"APELLIDOM": "MEJIA",
		"NOMBRECOMPLETO": "LIAM ROBERTO",
		"FECHANACIMIENTO": "10/14/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GMLR2013"
	},
	{
		"APELLIDOP": "GUATEMALA",
		"APELLIDOM": "ROMAN",
		"NOMBRECOMPLETO": "KIMBERLY ATENEA",
		"FECHANACIMIENTO": "3/7/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GRKA2013"
	},
	{
		"APELLIDOP": "LOPEZ ",
		"APELLIDOM": "AÑORVE",
		"NOMBRECOMPLETO": "JORGE GAEL",
		"FECHANACIMIENTO": "11/26/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "LAJG2013"
	},
	{
		"APELLIDOP": "MARTINEZ",
		"APELLIDOM": "PANTOJA",
		"NOMBRECOMPLETO": "VICTORIA ZOÉ",
		"FECHANACIMIENTO": "10/12/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "MPVZ2013"
	},
	{
		"APELLIDOP": "SILVA",
		"APELLIDOM": "REYNA",
		"NOMBRECOMPLETO": "AZUL ALITZEL",
		"FECHANACIMIENTO": "12/28/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "SRAA2013"
	},
	{
		"APELLIDOP": "TAVIRA",
		"APELLIDOM": "ORTIZ",
		"NOMBRECOMPLETO": "FRANCO",
		"FECHANACIMIENTO": "12/14/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "TOF2013"
	},
	{
		"APELLIDOP": "REYES",
		"APELLIDOM": "CASTELLANOS",
		"NOMBRECOMPLETO": "TADEO",
		"FECHANACIMIENTO": "8/2/2012",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "RCT2012"
	},
	{
		"APELLIDOP": "SANCHEZ ",
		"APELLIDOM": "GUERRERO ",
		"NOMBRECOMPLETO": "ANGEL SEBASTIAN",
		"FECHANACIMIENTO": "5/15/2013",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "SGAS2013"
	},
	{
		"APELLIDOP": "VAZQUEZ",
		"APELLIDOM": "GORDILLO",
		"NOMBRECOMPLETO": "GAEL",
		"FECHANACIMIENTO": "11/2/2012",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "VGG2012"
	},
	{
		"APELLIDOP": "ZARAGOZA",
		"APELLIDOM": "OLEA",
		"NOMBRECOMPLETO": "GENESIS AMANDA",
		"FECHANACIMIENTO": "12/27/2013",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "ZOGA2013"
	},
	{
		"APELLIDOP": "CALDERON",
		"APELLIDOM": "VEGA",
		"NOMBRECOMPLETO": "VICTOR GAEL",
		"FECHANACIMIENTO": "7/17/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "CVVG2012"
	},
	{
		"APELLIDOP": "CASTELLANOS",
		"APELLIDOM": "VALENCIA",
		"NOMBRECOMPLETO": "ALEJANDRA",
		"FECHANACIMIENTO": "7/19/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "CVA2012"
	},
	{
		"APELLIDOP": "GODINEZ",
		"APELLIDOM": "OCAMPO ",
		"NOMBRECOMPLETO": "NATALIA GETSEMANI",
		"FECHANACIMIENTO": "12/21/2011",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GONG2011"
	},
	{
		"APELLIDOP": "GONZALEZ",
		"APELLIDOM": "SALAS",
		"NOMBRECOMPLETO": "LUCERO DEL CARMEN",
		"FECHANACIMIENTO": "7/16/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GSLC2012"
	},
	{
		"APELLIDOP": "GUZMAN",
		"APELLIDOM": "VISCA",
		"NOMBRECOMPLETO": "ALEXANDRA YAMILET",
		"FECHANACIMIENTO": "5/25/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GVAY2012"
	},
	{
		"APELLIDOP": "HERNANDEZ",
		"APELLIDOM": "BAILON",
		"NOMBRECOMPLETO": "VANNIA MONTSERRAT",
		"FECHANACIMIENTO": "9/6/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "HBVM2012"
	},
	{
		"APELLIDOP": "JIMENEZ",
		"APELLIDOM": "NUÑEZ",
		"NOMBRECOMPLETO": "ALEXA",
		"FECHANACIMIENTO": "8/24/2011",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "JNA2011"
	},
	{
		"APELLIDOP": "LAREDO",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "ROSELIE SAMIRA",
		"FECHANACIMIENTO": "10/29/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "LCRS2012"
	},
	{
		"APELLIDOP": "MARTINEZ",
		"APELLIDOM": "SOBERANIS",
		"NOMBRECOMPLETO": "ADIEL ANDONI",
		"FECHANACIMIENTO": "1/21/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "MSAA2012"
	},
	{
		"APELLIDOP": "NATERAS",
		"APELLIDOM": "HIRUGAMI",
		"NOMBRECOMPLETO": "VALERIA",
		"FECHANACIMIENTO": "6/26/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "NHV2012"
	},
	{
		"APELLIDOP": "RAMIREZ ",
		"APELLIDOM": "GARCIA ",
		"NOMBRECOMPLETO": "EMILIANO VALENTINO",
		"FECHANACIMIENTO": "2/14/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "RGEV2012"
	},
	{
		"APELLIDOP": "RAMIREZ ",
		"APELLIDOM": "ROSAS ",
		"NOMBRECOMPLETO": "JACQUELINE JOLETTE",
		"FECHANACIMIENTO": "8/2/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "RRJJ2012"
	},
	{
		"APELLIDOP": "SANDOVAL",
		"APELLIDOM": "CAJIGAL",
		"NOMBRECOMPLETO": "MARCO ANTONIO",
		"FECHANACIMIENTO": "6/8/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "SCMA2012"
	},
	{
		"APELLIDOP": "SEVILLA",
		"APELLIDOM": "RAMOS",
		"NOMBRECOMPLETO": "EMMANUEL ABRAHAM",
		"FECHANACIMIENTO": "6/5/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "SREA2012"
	},
	{
		"APELLIDOP": "TRUJILLO ",
		"APELLIDOM": "PARRA",
		"NOMBRECOMPLETO": "AYLIN AMAIRANI",
		"FECHANACIMIENTO": "11/17/2012",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "TPAA2012"
	},
	{
		"APELLIDOP": "VERA",
		"APELLIDOM": "MENDOZA",
		"NOMBRECOMPLETO": "MARCO SILVIANO",
		"FECHANACIMIENTO": "12/31/2012",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "VMMS2012"
	},
	{
		"APELLIDOP": "AIRAGNES",
		"APELLIDOM": "CORTES",
		"NOMBRECOMPLETO": "BRUNO ROGER",
		"FECHANACIMIENTO": "3/7/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "ACBR2011"
	},
	{
		"APELLIDOP": "BRAVO ",
		"APELLIDOM": "VALVERDE",
		"NOMBRECOMPLETO": "JOEL IVAN",
		"FECHANACIMIENTO": "11/9/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "BVJI2011"
	},
	{
		"APELLIDOP": "CARMONA ",
		"APELLIDOM": "GUERRERO ",
		"NOMBRECOMPLETO": "JESUS SALVADOR",
		"FECHANACIMIENTO": "10/28/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "CGJS2011"
	},
	{
		"APELLIDOP": "CIENFUEGOS ",
		"APELLIDOM": "PALMA",
		"NOMBRECOMPLETO": "SOPHIA ISABELLA",
		"FECHANACIMIENTO": "4/5/2011",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "CPSI2011"
	},
	{
		"APELLIDOP": "DIRCIO ",
		"APELLIDOM": "SANCHEZ",
		"NOMBRECOMPLETO": "CARLOS ANTONIO",
		"FECHANACIMIENTO": "7/7/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "DSCA2011"
	},
	{
		"APELLIDOP": "GAMA",
		"APELLIDOM": "ZUÑIGA",
		"NOMBRECOMPLETO": "SOFIA ISABEL",
		"FECHANACIMIENTO": "12/30/2009",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "GZSI2009"
	},
	{
		"APELLIDOP": "MEJIA",
		"APELLIDOM": "CHAVEZ",
		"NOMBRECOMPLETO": "BONNY FERNANDO",
		"FECHANACIMIENTO": "5/31/2009",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "MCBF2009"
	},
	{
		"APELLIDOP": "MILLAN",
		"APELLIDOM": "LEAL",
		"NOMBRECOMPLETO": "MINET ALEJANDRA",
		"FECHANACIMIENTO": "11/1/2011",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "MLMA2011"
	},
	{
		"APELLIDOP": "MIRANDA",
		"APELLIDOM": "ELBJORN",
		"NOMBRECOMPLETO": "LESLIE RENATTA",
		"FECHANACIMIENTO": "8/8/2011",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "MELR2011"
	},
	{
		"APELLIDOP": "NAVARRETE",
		"APELLIDOM": "ALBARRAN ",
		"NOMBRECOMPLETO": "JOSE ANGEL",
		"FECHANACIMIENTO": "9/4/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "NAJA2011"
	},
	{
		"APELLIDOP": "TAVIRA",
		"APELLIDOM": "ORTIZ",
		"NOMBRECOMPLETO": "MIRTHA ELIZABETH",
		"FECHANACIMIENTO": "9/27/2011",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "TOME2011"
	},
	{
		"APELLIDOP": "TRUJILLO",
		"APELLIDOM": "ESPARZA",
		"NOMBRECOMPLETO": "LEONARDO",
		"FECHANACIMIENTO": "1/24/2011",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "TEL2011"
	},
	{
		"APELLIDOP": "VERDUZCO ",
		"APELLIDOM": "BUSTOS ",
		"NOMBRECOMPLETO": "ALEXANDRA",
		"FECHANACIMIENTO": "10/7/2011",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "SECUNDARIA",
		"MATRICULA": "VBA2011"
	},
	{
		"APELLIDOP": "MARTINEZ",
		"APELLIDOM": "LORENZANA",
		"NOMBRECOMPLETO": "DANIELA ANAHI",
		"FECHANACIMIENTO": "10/9/2010",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "MLDA2010"
	},
	{
		"APELLIDOP": "SUASTEGUI ",
		"APELLIDOM": "VALENTE",
		"NOMBRECOMPLETO": "SANTIAGO",
		"FECHANACIMIENTO": "3/8/2010",
		"SEXO": "M",
		"GRADO": "1",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "SVS2010"
	},
	{
		"APELLIDOP": "TORRES",
		"APELLIDOM": "JUSTO ",
		"NOMBRECOMPLETO": "ANAHI MIRETTE",
		"FECHANACIMIENTO": "6/30/2010",
		"SEXO": "F",
		"GRADO": "1",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "TJAM2010"
	},
	{
		"APELLIDOP": "BARRERA",
		"APELLIDOM": "QUEVEDO",
		"NOMBRECOMPLETO": "SANTIAGO",
		"FECHANACIMIENTO": "6/10/2009",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "BQS2009"
	},
	{
		"APELLIDOP": "ROBLES",
		"APELLIDOM": "JIMENEZ",
		"NOMBRECOMPLETO": "MANUEL DE JESUS",
		"FECHANACIMIENTO": "5/26/2009",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "RJMJ2009"
	},
	{
		"APELLIDOP": "RODRIGUEZ",
		"APELLIDOM": "CRUZ",
		"NOMBRECOMPLETO": "EMMA IVANNA",
		"FECHANACIMIENTO": "5/19/2009",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "RCEI2009"
	},
	{
		"APELLIDOP": "TORRES",
		"APELLIDOM": "GONZALEZ",
		"NOMBRECOMPLETO": "ALLISON DAMARIS",
		"FECHANACIMIENTO": "11/2/2009",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "TGAD2009"
	},
	{
		"APELLIDOP": "TORRES",
		"APELLIDOM": "JUSTO",
		"NOMBRECOMPLETO": "CRISOL ANDREA",
		"FECHANACIMIENTO": "8/30/2008",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "TJCA2008"
	},
	{
		"APELLIDOP": "TRUJILLO ",
		"APELLIDOM": "ESPARZA",
		"NOMBRECOMPLETO": "MARLEY MONSERRAT",
		"FECHANACIMIENTO": "5/8/2009",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "TEMM2009"
	},
	{
		"APELLIDOP": "VARGAS",
		"APELLIDOM": "VINALAY ",
		"NOMBRECOMPLETO": "ANA LAURA",
		"FECHANACIMIENTO": "9/16/2009",
		"SEXO": "F",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "VVAL2009"
	},
	{
		"APELLIDOP": "NAVARRO",
		"APELLIDOM": "MENDOZA",
		"NOMBRECOMPLETO": "ANGEL",
		"FECHANACIMIENTO": "9/7/2009",
		"SEXO": "M",
		"GRADO": "2",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "NMA2009"
	},
	{
		"APELLIDOP": "BUTRON ",
		"APELLIDOM": "DAZA",
		"NOMBRECOMPLETO": "ISABELLA GUADALUPE",
		"FECHANACIMIENTO": "12/4/2008",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "BDIG2008"
	},
	{
		"APELLIDOP": "FENTON",
		"APELLIDOM": "CASASOLA",
		"NOMBRECOMPLETO": "AWBREY XIMENA",
		"FECHANACIMIENTO": "5/4/2008",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "FCAX2008"
	},
	{
		"APELLIDOP": "OCAMPO",
		"APELLIDOM": "ESTAÑON",
		"NOMBRECOMPLETO": "JORGE ELIAS",
		"FECHANACIMIENTO": "1/16/2008",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "OEJE2008"
	},
	{
		"APELLIDOP": "ROMAN",
		"APELLIDOM": "MARTINEZ",
		"NOMBRECOMPLETO": "EVOLET",
		"FECHANACIMIENTO": "8/8/2008",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "RME2008"
	},
	{
		"APELLIDOP": "RODRIGUEZ ",
		"APELLIDOM": "LUVIANO",
		"NOMBRECOMPLETO": "ABRAHAM ABISAI",
		"FECHANACIMIENTO": "10/24/2025",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "RLAA2007"
	},
	{
		"APELLIDOP": "SABINO",
		"APELLIDOM": "VELAZQUEZ",
		"NOMBRECOMPLETO": "ANA LAURA",
		"FECHANACIMIENTO": "2/11/2007",
		"SEXO": "F",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "SVAL2007"
	},
	{
		"APELLIDOP": "VARGAS",
		"APELLIDOM": "VINALAY",
		"NOMBRECOMPLETO": "RICARDO",
		"FECHANACIMIENTO": "8/13/2008",
		"SEXO": "M",
		"GRADO": "3",
		"SECCION": "PREPARATORIA",
		"MATRICULA": "VVR2008"
	}
]

module.exports = data;